### ISSUE TITLE
Support paths without quotes

### ISSUE THREAD

**Issue by devantler** [ascpixi/vscode-path-go-to-definition#3]
In YAML, it is quite common to not add quotes around strings, so it would be cool if this extension is able to support go to definitions for those paths as well.

**Comment by ascpixi** [comment]
Implemented in 1b38fb4.

**Comment by ascpixi** [comment]
In YAML, this may be used as follows:

```yaml
"pathGoToDefinition.specific": [
    {
        "language": "yaml",
        "pathStringRegex": "^.+: *(.+)$"
    }
] 
```

This will match all values in `<key>: <value>` pairs as strings, meaning that `example: my-path.txt` will allow for F12 to be pressed while the cursor is on `my-path.txt`.
